# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
        migrations.RenameModel(
            old_name='Owners',
            new_name='Owner',
        ),
    ]
