# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0003_auto_20180120_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='device',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dataview.Device'),
        ),
    ]
